version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - alex_pgdata:/var/lib/postgresql/data
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - "5433:5432"
    volumes:
      - alex_pgdata_test:/var/lib/postgresql/data
    networks:
      - custom
  my_pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: anton@domain.com
      PGADMIN_DEFAULT_PASSWORD: Anton
    ports:
      - "80:80"
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  alex_pgdata:
    external: true
  alex_pgdata_test:
    external: true