version: "3.0"
services:
  # app:
  #   build: .
  #   volumes:
  #     - ./:/app
  #   ports:
  #     - 8000:8000
  #   container_name: my_back_end
  #   depends_on:
  #     - db_app
  db_app:
    container_name: "db_app"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - alex_pgdata:/var/lib/postgresql/data
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  alex_pgdata:
    external: true
