"""nikolai added new column tg_user_id tg_user_name card_status

Revision ID: a44c1a8b19cb
Revises: 61ab3f614c77
Create Date: 2023-03-23 20:07:27.808371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44c1a8b19cb'
down_revision = '61ab3f614c77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('tg_user_id', sa.String(), nullable=True))
    op.add_column('card', sa.Column('tg_user_name', sa.String(), nullable=True))
    op.add_column('card', sa.Column('card_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'card_status')
    op.drop_column('card', 'tg_user_name')
    op.drop_column('card', 'tg_user_id')
    # ### end Alembic commands ###
