"""column query_time in code

Revision ID: 5f0ca0091ee5
Revises: 4bf9a7094554
Create Date: 2023-03-23 09:20:53.982660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0ca0091ee5'
down_revision = '4bf9a7094554'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('query_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'query_time')
    # ### end Alembic commands ###
