"""uniq deleted

Revision ID: 6f0aeb8af970
Revises: c268317bb8d8
Create Date: 2023-01-24 22:46:10.372868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0aeb8af970'
down_revision = 'c268317bb8d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_inv_key', 'card', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('card_inv_key', 'card', ['inv'])
    # ### end Alembic commands ###
