"""changed the column property in card

Revision ID: 61ab3f614c77
Revises: 5f0ca0091ee5
Create Date: 2023-03-23 09:50:06.808163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61ab3f614c77'
down_revision = '5f0ca0091ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'digi_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'digi_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
