"""new DB

Revision ID: 4bf9a7094554
Revises: 
Create Date: 2023-03-23 00:48:38.747562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4bf9a7094554'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('card_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('card_code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('inv', sa.Integer(), nullable=True),
    sa.Column('is_received', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('added_time', sa.DateTime(), nullable=False),
    sa.Column('used_time', sa.DateTime(), nullable=True),
    sa.Column('digi_code', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('amount_tl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('code',
    sa.Column('code_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code')
    op.drop_table('card')
    # ### end Alembic commands ###
