"""initial

Revision ID: 3545ae222ee4
Revises: 
Create Date: 2023-01-18 23:43:09.993045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3545ae222ee4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('card_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('card_code', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('inv', sa.Integer(), nullable=False),
    sa.Column('is_received', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_tl', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('card_id'),
    sa.UniqueConstraint('inv')
    )
    op.create_table('codes',
    sa.Column('code_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codes')
    op.drop_table('cards')
    # ### end Alembic commands ###
